-- USERS / PROFILES
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text check (role in ('owner','admin')) default 'admin',
  created_at timestamptz default now()
);

-- STOCK ACCOUNTS
create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  service text not null,
  email text not null,
  password text not null,
  profile_name text,
  pin text,
  capital numeric(10,2),
  price numeric(10,2),
  added_at timestamptz default now(),
  sold_by uuid references public.profiles(id),
  sold_at timestamptz,
  status text check (status in ('available','sold')) default 'available'
);

-- ACCOUNT RECORDS
create table if not exists public.account_records (
  id bigint generated by default as identity primary key,
  account_id bigint references public.accounts(id),
  product text not null,
  buyer_username text not null,
  admin_id uuid references public.profiles(id),
  availed_at timestamptz default now(),
  duration_days int not null,
  extra_days int default 0,
  expires_at generated always as (availed_at + (duration_days + extra_days) * interval '1 day') stored
);

-- Function to mark as sold and record transaction
create or replace function public.sell_account_and_record(
  _account_id bigint,
  _buyer_username text,
  _duration_days int,
  _extra_days int default 0
)
returns void language plpgsql security definer as $$
declare
  me uuid := auth.uid();
  role text;
begin
  select role into role from public.profiles where id = me;
  if role != 'admin' then
    raise exception 'Only admin can sell.';
  end if;

  update public.accounts
     set status='sold', sold_by=me, sold_at=now()
   where id=_account_id and status='available';

  insert into public.account_records(account_id, product, buyer_username, admin_id, duration_days, extra_days)
  select id, service, _buyer_username, me, _duration_days, _extra_days
  from public.accounts where id=_account_id;
end $$;

-- RLS
alter table public.profiles enable row level security;
alter table public.accounts enable row level security;
alter table public.account_records enable row level security;

create policy "Owner can view all" on public.accounts
  for select using (exists(select 1 from public.profiles p where p.id = auth.uid() and p.role = 'owner'));

create policy "Admin can view own" on public.accounts
  for select using (status='available' or sold_by = auth.uid());

create policy "Admins can insert/view own records" on public.account_records
  for all using (admin_id = auth.uid()) with check (admin_id = auth.uid());
